P4CONFIG: null_p4config
P4PORT: ssl:main.commit.helix:1666
P4USER: bot_HRA_instance_monitor
P4CLIENT: bot_HRA_instance_monitor_ws
P4TICKETS: /home/datapushgateway/.p4tickets
P4TRUST: /home/datapushgateway/.p4trust
P4PASSWD: bot321!!
